apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-yaml
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: https://github.com/PARK-HEECHAN/devops_k8s.git
    targetRevision: cicdstudy
    path: sample-yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground