replicas: 1
image:
  repository: 489527167655.dkr.ecr.ap-northeast-2.amazonaws.com/demo
  tag: 1.0.7
  imagePullSecrets:
    - name: regcred
      # imagePullPolicy: Always
service:
  type: NodePort
  protocol: TCP
  targetPort: 8080
  port: 8080
  nodePort: 31080
ingress:
  enabled: false
